---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vault-credentials
  namespace: prefect-worker-basedosdados
spec:
  encryptedData:
    VAULT_ADDRESS: AgCsVaudxt8vU2XxRC/bKRflTm0Xlxf3I49jwP+wnkFq1JfOlus/td8A5YDsl5Ulrs6tVW3MWAOQsEuP9RHMPPALCRV7iZd7V5AK/VN9LwiHYUz6CT2OyXzGccOHtLlZ/oSi4MJ3J8c0msLZMSM9YOYeojVkk6vlf923D2PpQnUCrr6ag5lfvgLWxfeNflpipNpG+iNPy7EYQgfw8nMtDpher1pNKKPhuR0IGSoroGeh3L+XWuOdbVXi5LD6I3SAIHE8CS+Lvq+cN2f2dQulyUGR+T0jGWPeq/+hHRg/M2IkFxTArjhaTrmqKaYzeZQSc+eTsKcZvJbDoA7tCubq/PAq5+evWCskdWRrFT6a6tC0aA9ltgE18vesPrXLAVkEhlpwXLFoepTQA/iSh1pvf/o4Tr+ICNftrzPbyLN5p0HzzAoHgoiVD5Pk8BamDmDAHbIBIVBIYihUb/nrByBLlL+VCSSSerdOgOfj/5oJgMqVBiXs6jNrTVavNdtNGoYM788OepBhkBFTSwN7oHGwHPHtJMCGWo+3IZIsEywccXgubqRs1kPUWfTsYbykpUDzy0hgohbQjN3tr9nb45/6k1zjqqMtqIAairs7dYbHKplIjnsmx3iDiGznfyGz6TRf8AW9ta2rA0VA9Y4NpWyf4vKEhgsOVFo0J8NM7l31Q2LvoKZWQzQZy4lPnqYnckYv4Vbo12AWPd8tgLeXAAkFpZJ9mCwon0o5GEEAKJzen/fX8dXf7vdnhbu7n2U=
    VAULT_TOKEN: AgBdjnZYqPlPFAd7ABKjieMZcP8FsdoyuPqVFi1w2yq+cA9Ln0sagzMMJ/RQ5dHxS+OELaRqNU2Z60+4HkHCokSh5TcldBv0ugbADy/xBG2UPCNdUyhYufkW0B/Qsd0wbGHAv0xtaK2eDu1jgzLDunpHuXENHWACZ7l7AtemwWQZQenKazO2x8Q+JyuPZR1xgRpJgPLZbqhgUqBP66JeyJxdtgPCmMohtYXSTTAw4mSoQNMbXy2jf11HyY9jP/0IQkauh1BBRl4GEgUtagIwCPQ29KPhtzVnlB8IiMXdpOu00HHN2x5UtUUcqNgb/ybwkhzLGcAWgbdarSpE/k0fRwhteDnT4c/otCyq8BRRDCrlrEhQiUZ/W+8UMC0nRNndEgJ7YQMwlwhlNSsa65oMStJQxD/Pencq1+NAwSEib5O3n64moRKg/rO5d0zFXedCauF/EM/NdE8g9xCql/rIvksQZ7DWLCmSo6GCPJR1D8e73ji7ZaVvhDoFxbSY+PqYjMI+s7rA1IVG73MB1/F4o/vSzHeDy6O1ol0NVlc+TykDaS2JB7ObRHcIpTkVdvSDeYZRqVh7nBiP+Fm8GyPC96NRf+7FSxvMosSyhlPceZZzZPlezbbYTM9qRqT58QrfVB0+KcaEMpTB1dk1UdyQcDV4xw5WQgi5mHrudC5FB6H6l3pNBwmmYOgp21+8nCuQQ2K/2C0mHbMU12n+7O5ljmUGML64oHj10qlzdw==
  template:
    metadata:
      name: vault-credentials
      namespace: prefect-worker-basedosdados
    type: Opaque
