apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-keys
  namespace: prefect-worker-basedosdados
spec:
  encryptedData:
    BEA_API_KEY: AgCnK99SwtaEwW4kizlrSaJATYh76z9fv5LfH0WP57aHNJR0OKMIzkNwEayQV6q9qn+zJEioIY8IUN4jfoeGwdTO84Q//+1uufw3wlqxRFVY1iLm8ZuIQXGaU5Q3AhHD9946qMs2J5/pMZoAn/v44Hewjsiey6YHH3bSAl6mxggceYVIGIgs8q5CJBflM9D7WCKfRG5H3aqWWXSCZ51VzptvRwZVHPEDzJQyBFyumNIxJEC1GaZD8BMJ352YrbkuETKAMK2ALRV/tZjszQ4OfSP1VbZi93wUsbdb6NsoDIcni4bjdU923NFPg/80EvsQbL0G/Bdcw0VR6Y+sMmi8wr9B2jSgIRAVcUTu42nVPYnde506s1oeV3aw9PAglnhpae9k38znHwAkaWok5XMceCASUfiKpj0dBh3qPkhsHKmQaAeYepxy0QRkH+JHYXoh87WvyQfIwOP6xi/n6wsOpYtEGAM4TM2jz/QrjBPAmjXCa6hDOBRWyf9fTAQe8zfw+6gu4T+APD2Y3yf29fWdfY18QN8+3LzKTeNfj0z83xTTv1rv6JKW1oYH4lr+HcNEZvFzTGvbOnIBhFaDgUsxRZFv3ZSOfZE3VITFOHTYS5yIm5o9vuZL9907imQyq2/gJXgjLz/jb7vLgPrAlir5CLNVVY3hM+paJtUisyUESv/5FwLIM0HdKrsj/dKW4wIwyf53pe01ZPJg0Elv8Sev4PSMQYn4j06CcbxMN8DdDDbLby36T2Q=
    FRED_API_KEY: AgAUUOesBaly6xvFX8aVYasUao63e3BcaNRc8FTWXBjCmW1itJ30RrNrFPAYp1Ge8a1B7ZJ7TbwgnxQq7nxJv3WG3VsOpTNx7IfZ5Q4sxtu5tJAjHjteATC5Cfl0sN2lBzkc/AmjJQoC1hJ+5XOOALobavERGGJ20KdtBUkQg7RCqcpllVFxonnTaEbndxeHuVpaT0wgIeKcP7hixtnyzA1oDyuW9+xFw0UV5ZWoi6uuhavvxPxKjBrPem+kRUbvLiH547yrPVATfwaNnjDK/Gf1Z6UcLdhBKzZPza6IebaX0oCa3sugKhJmvtkGiaDnxexQ7gImx1imYm9QlRYfGu4cRL6DDuJoCR8yBEUnP2+dwwr390xtK6pxxtjkiwIDlkzbE24EFw4E7rSkKOwxoP0TDanUjpldyKZ5hlhiOLB8vkoQWgTNkx+Gyl+rr8/rUZ5e+QaD0j3z8CQt7z6CFpFd3ivX5vFrByBoy0pBEy+A38htZNxg+owzD9EwQFfqLAPGuRoA57AuyocCpGn9Mb8KADgxv2XzigJx12uc/4z46nltdwSL65IYm4kSnLNs3gDRihhYDXl6qyON+2i0a3vOnm1EaT3n6el4KtU1o2ezvsTZo1G3vhDXN9MWTl6M6AGdfWTjj1caaf3dRcJ3tf4zrsv5ej6Oej6/461MGA2grh85Q6Tw0h942bcc0+aBepwGzcnXGR73nIvoAKDcZdqO1JjqRfyu5JuWJj02rn+jtA==
  template:
    metadata:
      name: api-keys
      namespace: prefect-worker-basedosdados
    type: Opaque
