version: '3.9'

services:
  bd_terraform:
    env_file:
    - ./terraform/.env
    image: hashicorp/terraform:1.1.9
    container_name: bd_terraform
    volumes:
    - ./terraform:/iac
    working_dir: /iac
    command: [init]
