apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-sql-instance
data:
  CLOUD_SQL_INSTANCE_NAME: basedosdados-dev-postgresql
  CLOUD_SQL_INSTANCE_REGION: southamerica-east1
  CLOUD_SQL_PROJECT_ID: basedosdados-dev
