apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloud-sql-proxy
  name: cloud-sql-proxy
spec:
  ports:
    - port: 5432
      protocol: TCP
      name: cloud-sql-proxy
      targetPort: 5432
  selector:
    app: cloud-sql-proxy
