# helm upgrade -i -n observability -f values.yaml loki-stack grafana/loki-stack

loki:
  enabled: true
  isDefault: true
  url: http://{{(include "loki.serviceName" .)}}:{{ .Values.loki.service.port }}
  readinessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45
  livenessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45
  datasource:
    jsonData: '{}'
    uid: ''
  persistence:
    enabled: true
    size: 100Gi

promtail:
  enabled: true
  config:
    logLevel: info
    serverPort: 3101
    clients:
    - url: http://{{ .Release.Name }}:3100/loki/api/v1/push
