apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp:
  name: vault-credentials
  namespace: prefect-agent-basedosdados
spec:
  encryptedData:
    VAULT_ADDRESS: AgBbp7wVFg+XwlvSsw6565NNH1dXydqXgxuAwn1Zw+yVKtduDmrU1QLjswh4meE6HjLJEZ3+mG1DqqjT2xQH3lAw8WAZWUwYBjbQ0N/fYAWZVZmrqjJUyK9y7Uqu8gr7GqQz4zDQ0JPoWGvtIaxqL+eYM6f/mCAZM3AcEa5mEx/sI7pCCiRYl93QyBG5WyYTmw0cPCkmF2wy4+0y0o662oy2WsUmWfFyw+2ZE2RF7pTIwjjePbMh7ctHEOWgCJSBoV/9Yi84NoOiLJPcIf0PAnYAD7431I2kkcPBFcxx0qgfn2jD/prScgRGiJb4R+AC6+WjhJqTvUWkJCqSL6fCvt9q1J2HzGZFLdFgVqF+OVkfibJdWZZM74lvHpwzls7oc4H6RJJZ7sN1ZBOqmNiUcfs2SMTBNb1v8QWt6Qw3cLgHUqWaCnH1rWDsdtdrEz+9FG4LkVxQbBhRonmXFjD0cN4EI1Gg09HnuMg5nS4k83PD3be365CpPAKGOtsvc389lWo7je+N/EsP7yosMx1t6uYdxxQCXTDK3/DHx1VkGo4aNSq3XCteIrRyG1FWRjwTsCL3K8YMbIA8o6i09ZlosHNpdtsUyzTmocrNUJ2yNIPCqeqth9PqFxd+4zMNHMu9GK8P+Hf0+gxMFgZfOPqLKZvalEYS9muoOK+y05Xd1Sz5bwYJmjyY1SZvghIyZnL6MT4jRqz9x0olNxLPZ3NEpZfd5TNnewcMDmUyYbUPhVNs3HeD5pNWCD31k/k=
    VAULT_TOKEN: AgBW3Yzkw9Smqkkvde/nh7hCstSPe1VkdIw24XunE1CeWd4p/cmK5pjqzneLG2sQPCPPjTrccYyRkCf5R/uHfKeXrRQJFMV4fxAT0+Wf8iZKhalsvqlY+ng76QsE8GmexzznrHBiMCI5xFFZxIctUqY+lJnlYVEDze7iKiv2Ucs3RjTS53afWOr988R65tRNT+HQIibcSvivDhzQKHrXQs/dVbTs2/UL1iFVW6DRcNOhjm/liPRsf1n0Wu4iN4QAsNvGuOfrPCiTNKRubsX88XdpWl1ztLy8YtfAKvKaU7mDP1NNsljy3lljnqw/UHKauso2aeo319tc8Uiyge5Gp9cVL/D9F0xJqx0iFP+k+60USqwqwO6bdu/2E2IZluRrHbjyQmJQoUjMXAR9i7sXDecXPoUgpRYG2qGd23NiK/8e4A3pmXcvL/GIunMUZ+3CdrpJVQ+fVuyQ9l2CV333VZWw4TesRBpUeX1OVjYVH+GCRpTCBzlbb5p7hEjEs/vPlrkVRmVIy9htQjAXrDkRSJdXci2im8CxhaMSNKiD9IGmlFWl0NzXCJPGZkMYjubl7RXk/kdRgaug/hvvBGeDClezD2Ha5JuZAE9KoVtHtTkahEVKe8FGq8hErpt6lCOKm/er1iBYNHNANYmDX0B8x+ZM8ga/3v5uq5sL5UOke5px3Gy1KcsPr4enikKOkZkPbX/160i8uRb4koM0tyTXvWRBYXiynv6Eao0I2g==
  template:
    data:
    metadata:
      creationTimestamp:
      name: vault-credentials
      namespace: prefect-agent-basedosdados
