---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vault-credentials
  namespace: prefect-worker-basedosdados-dev
spec:
  encryptedData:
    VAULT_ADDRESS: AgAYOg2xfjLDVLm/7OCir6aEThyBVeZQWDVA6iNN/hsc1EFzjWBf1jH4BseBQ0xoncCVuO1gXAXd4BxGvD35nvT2hAvfT7GKLJ1d5cTUE71gjw2xoTmTH3KYhMWJs9YQE4JoylMbL4QZQzeg98cQPMfhTGXQ6R5BMo8MiCGPqzX1SrUVigH7bwTYvWHQbnn8fQo9NG/7meD9i/xuxWqdEwItNEFCBsOq6smtE53PSm1CIdwwW7hHfiTDvW8rVHrqdimIQwSO2qws2gajGV41nwtgkYaZ3hRGOpkIT/bBDNlDA2hdLKN16A9KrqTp42ue7IWlnJryOKHsYonefEYGEKMSHprtTDETnjhL4jwHWoQ+8osalsQLIQlvpUjboJ4X04l+VpNVW/mbynS/gI/za8RrOqjj7S6dQu0eHkc+bPIKQojTrn71/gYbLAaNoQqRxHtBNOK/7PRF5EJz+nwsKKVAgybOwds35J0zpGp5XE1V7AeSmz5pd0+KJ5lE7ao0tBRj2NuOIx8PkQhnizkfIwCspAaPo8iygp+KBVXdmrebWahdQSGNcO4yGyD0nS4pgvWIS/c83H532uaC16cDUBVVDuw0wZdCNlPpjzcidSpqj1J5hqhoDIrO03sRxm0wyZ3CRMl3heElnMfHVgEA5jsI3Mr5dVoGg9LrDfmwsWxfx3vimK5a3jX9lK8wZMTVwZoNZpJ030SBODcFWGvAAOm5b1JgTeD5chMCpct6JFrcDXQY8jLdryeBceI=
    VAULT_TOKEN: AgCEwDkA6MemM6Ec5G82d040y2uw+zDF/u2R4Nc14ADSxr02GBrniTucJmH9V431kQc+5HYLLhkpBzMncC/gpQmFn1OhPlgOatBATxKtLtomRwTzoDxYq2yMBkTDXeNDCuIDFGfox9sPXsmSmOuDeXiqG+5qfQWIBECP1K4iutGeAHURL+EUtRzgiV4Dh95QifY82CputFCbipCWGIRuNmrjmYdqwQtNVVj1jIXURdqst+QoG6DtcyXU9DtzzkaBd77xbUKZJm4SJgITuxDKNVlndjB5i0NWgLRVNh1p6ij4XLcJ+wGV1jEH7ShrYbvE4kqI0FNRluy4BdBNiouY9DsaaCrjq4XACN69mMs+6cOJ0FZtnrJr3R/YmaUZk/v2O0LOi37c6f9BDbU6RyelcrJz+jGkPhjYsL47yHBj2Aq/HUFj93fTnxFONMW+e4kdMRRASKt2TfUNBOGxWfloJqPgVCkBNGfa8Dg4OcyxsMx9my3gWEf5WDGAtGE8P4MO9pmifvfkF12Lqg7OF2e3s++aM0m/lX+LBs9hfGSggs7ekQ5moLG0jcUH5dZOsjMv0EYcuuRl0sa3pD4rqAevb/MEzITQTMPKr0xLSSycEOFBJCBd/TLD2XgHuRW2TGfNnrE7MPikKi9K0iIWm3Z4Tivh8p3Rki8ODRHjsGhdWmi/QIw4FQ63lAekZqfobyg4cebc8m4XITIef2vS2WgJeg50r8pLnrY3tn6Leg==
  template:
    metadata:
      name: vault-credentials
      namespace: prefect-worker-basedosdados-dev
    type: Opaque
