---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prefect3-db-connection
  namespace: prefect3
spec:
  encryptedData:
    connection-string: AgA8wR8TsGacrw3ISWZ4vCF6GVZZWibpSxdv3e3jcDded0u5c14jiWSklfpqi88N0P5ROGki/3CWjuCjXNnJf+W0AjC97fUxkLbOAhH32wVdlnzOn00jHCFHRI4zZoqeyOpae7fbamtt3uTIeQK/dgeEvN55fQS0cJ5rVfuY90+L77C6uPd3rfSy4iqs9Cldm3nvSuAuGPrdq3Yiqho+FAgsBeK/wbSx3ia56fIpCztX9H1HhjfHu3syyLkyN7EzE6TbzDRYpPWGJdKuL4UUl+RIou8tphPXuJO57HlrZuEZJRxINwPC22rVOQ62YawIqndRyiewz/OvVtb2nTyJ+YQ3+2e9586ptjNx6NNfH1/D4grRgTJvjgtfRpy6PIhp9rKFtSMOWALD2lIM8nMlBE/47Eakg+Jh1Y381ZW2VY9h6S0KdoykIpaOdPH8F7N0Jmk1LPymDPpbn0JcOgxsmQVoBgyLV6N9mln3VTI6T1eCEPoRej5KMqDBzg+MDeaYypNFErHV9gsw69/H9QvYpfw+jH94A+u+YsNTc8N77dpJu2I1OPB8D8dAkkrE3F4dEQGJbMgnLo1uaS1ChOEueT0aN78AT5qBzq6mvfv1iokvaHCmUOjsbxeqexbHqjrWzMTTZRZAYqmxmZJJXgjnfIiRemR6yeGs4wdx/+HYhWdCfIrhh/zyAiQSTvwTfE0worE064tVRMH7BB1th/GeIZbyidx639rSYu8tion6mWdTE39prvwLYxCjYkQf71DqRAgOMiu1cvwPAJEF96UNDWrk9CuqYw0vdH4ClLyxl5ZT7k/kTUGIWfXp
  template:
    metadata:
      name: prefect3-db-connection
      namespace: prefect3
