# helm upgrade --install prefect-agent -n prefect-agent-questions ../../../../charts/charts/prefect-agent/. -f values.yaml

agent:
  apollo_url: http://prefect-apollo.prefect.svc.cluster.local:4200/
  env: []
  image:
    name: prefecthq/prefect
    tag: 0.15.9
  job:
    resources:
      limits:
        cpu: ''
        memory: ''
      requests:
        cpu: ''
        memory: ''
  jobTemplateFilePath: https://storage.googleapis.com/basedosdados-dev/prefect_job_template/job_template.yaml
  name: prefect-agent
  prefectLabels:
  - perguntas
  replicas: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
  serviceAccountName: prefect-agent
