apiVersion: v1
kind: Secret
metadata:
  name: grafana-datasources
  labels:
    grafana_datasource: 'true'
stringData:
  loki.yaml: |-
    apiVersion: 1
    datasources:
      - name: Loki
        type: Loki
        url: http://loki-stack.observability.svc.cluster.local:3100
        uid: "salmon"
        access: proxy
        isDefault: true
        editable: false
        basicAuth:false
        jsonData:
          timeout: 60
          maxLines: 1000
