# helm upgrade --install prefect-agent prefeitura-rio/prefect-agent -n prefect-agent-basedosdados-projetos -f values.yaml

agent:
  name: prefect-agent
  type: kubernetes
  vertexRegion: ''
  vertexServiceAccount: ''
  prefectLabels:
  - basedosdados-projetos
  replicas: 1
  image:
    name: prefecthq/prefect
    tag: 0.15.9
  serviceAccountName: prefect-agent
  jobTemplateFilePath: https://storage.googleapis.com/basedosdados-dev/prefect_job_template/template.yaml
  apollo_url: http://prefect-apollo.prefect.svc.cluster.local:4200/
  prefect_backend_server: true
  auth_secret_name: ''
  gcp_sa_secret_name: ''
  job:
    resources:
      limits:
        cpu: ''
        memory: ''
      requests:
        cpu: ''
        memory: ''
  env: []
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
