apiVersion: batch/v1
kind: Job
spec:
  template:
    spec:
      containers:
      - name: flow
        envFrom:
        - secretRef:
            name: gcp-credentials
        - secretRef:
            name: vault-credentials
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /mnt/creds.json
        volumeMounts:
        - name: gcp-sa
          mountPath: /mnt/
          readOnly: true
        - name: credentials-dev
          mountPath: /credentials-dev/
          readOnly: true
        - name: credentials-prod
          mountPath: /credentials-prod/
          readOnly: true
      volumes:
      - name: gcp-sa
        secret:
          secretName: gcp-sa
      - name: credentials-dev
        secret:
          secretName: credentials-dev
      - name: credentials-prod
        secret:
          secretName: credentials-prod
