# helm upgrade --install prefect-agent prefeitura-rio/prefect-agent -n prefect-agent-basedosdados-dev-gcp-vertex -f values.yaml
agent:
  name: prefect-agent
  prefectLabels:
  - basedosdados-dev-gcp-vertex
  serviceAccountName: prefect-agent
  replicas: 1
  image:
    name: prefecthq/prefect
    tag: 0.15.9
  jobTemplateFilePath: https://storage.googleapis.com/basedosdados-dev/prefect_job_template/job_template.yaml
  apollo_url: http://prefect-apollo.prefect.svc.cluster.local:4200/
  job:
    resources:
      limits:
        cpu: ''
        memory: ''
      requests:
        cpu: ''
        memory: ''
  env: []
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
