# helm upgrade -i -n observability -f values.yaml loki grafana/loki

deploymentMode: SingleBinary
loki:
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: 2024-04-01
        store: tsdb
        schema: v13
        index:
          prefix: index_
          period: 24h
        object_store: filesystem
  storage:
    type: filesystem
  auth_enabled: false
test:
  enabled: false
lokiCanary:
  enabled: false
singleBinary:
  replicas: 1
  persistence:
    size: 100Gi
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
