name: Continuous Deployment [Terraform]

on:
  push:
    branches:
    - main
    paths:
    - terraform/**

jobs:
  cd-terraform:
    name: Continuous Deployment [Terraform]
    runs-on: ubuntu-latest
    env:
      tf_actions_working_dir: terraform
    environment:
      name: development

    defaults:
      run:
        shell: bash
        working-directory: ${{ env.tf_actions_working_dir }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Import Secrets
      id: import_secrets
      uses: hashicorp/vault-action@v2.4.1
      with:
        url: https://vault.basedosdados.org
        token: ${{ secrets.VAULT_TOKEN }}
        secrets: |
          secret/data/terraform_credentials    GOOGLE_APPLICATION_CREDENTIALS    | TF_VAR_GOOGLE_APPLICATION_CREDENTIALS ;
          secret/data/ckan_credentials         sql_ckan_production_user_password | TF_VAR_sql_ckan_production_user_password ;
          secret/data/ckan_credentials         sql_ckan_staging_user_password    | TF_VAR_sql_ckan_staging_user_password ;
          secret/data/metabase_credentials     sql_metabase_user_password        | TF_VAR_sql_metabase_user_password ;
          secret/data/prefect_credentials      sql_prefect_user_password         | TF_VAR_sql_prefect_user_password

    - name: Create .tfvars file
      id: create_tfvars
      run: |
        echo 'sql_ckan_production_user_password = "${{ steps.import_secrets.outputs.TF_VAR_sql_ckan_production_user_password }}"' > variables.tfvars
        echo 'sql_ckan_staging_user_password    = "${{ steps.import_secrets.outputs.TF_VAR_sql_ckan_staging_user_password }}"' >> variables.tfvars
        echo 'sql_metabase_user_password        = "${{ steps.import_secrets.outputs.TF_VAR_sql_metabase_user_password }}"' >> variables.tfvars
        echo 'sql_prefect_user_password         = "${{ steps.import_secrets.outputs.TF_VAR_sql_prefect_user_password }}"' >> variables.tfvars

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.9

    - name: Terraform Init
      id: init
      run: terraform init
      env:
        GOOGLE_CREDENTIALS: ${{ steps.import_secrets.outputs.TF_VAR_GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve -var-file=variables.tfvars
      env:
        GOOGLE_CREDENTIALS: ${{ steps.import_secrets.outputs.GOOGLE_APPLICATION_CREDENTIALS }}
