name: Continuous Deployment [Terraform]

on:
  push:
    branches:
    - main
    paths:
    - terraform/**

jobs:
  cd-terraform:
    name: Continuous Deployment [Terraform]
    runs-on: ubuntu-latest
    env:
      tf_actions_working_dir: terraform
    environment:
      name: development

    defaults:
      run:
        shell: bash
        working-directory: ${{ env.tf_actions_working_dir }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Import Secrets
      id: import_secrets
      uses: hashicorp/vault-action@v2.4.1
      with:
        url: https://vault.basedosdados.org
        token: ${{ secrets.VAULT_TOKEN }}
        secrets: |
          secret/data/terraform_credentials GCP_SA                | TF_VAR_GCP_SA ;
          secret/data/terraform_credentials TF_VAR_SENSITIVE_DATA | TF_VAR_SENSITIVE_DATA

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.9

    - name: Terraform Init
      id: init
      run: terraform init
      env:
        GOOGLE_CREDENTIALS: ${{ steps.import_secrets.outputs.TF_VAR_GCP_SA }}

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Apply
      id: apply
      run: |
        echo "$TF_VAR_SENSITIVE_DATA" > .env
        source .env
        terraform apply -auto-approve
      env:
        GOOGLE_CREDENTIALS: ${{ steps.import_secrets.outputs.TF_VAR_GCP_SA }}
        TF_VAR_SENSITIVE_DATA: ${{ steps.import_secrets.outputs.TF_VAR_SENSITIVE_DATA }}
