name: Continuous Integration [Terraform]

on:
  push:
    branches:
    - main
  pull_request:
    paths:
    - terraform/**

jobs:
  continuous-integration-terraform:
    name: Continuous Integration [Terraform]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Files
      uses: Bhacaz/checkout-files@v2
      with:
        files:
        - terraform

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
